settings:
  title: 'Createch Status Page'
  url: 'https://status.createchstuido.com' # used for Slack messages
  logo: 192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: env-share # unique identifier
    name: Createch Env Share
    description: 'Share your environment key in a secure way.' # default=empty
    url: 'https://envshare.createchstudio.com/share' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: support
    name: Createch Support
    description: 'Your job is to create, our job is to help you.'
    url: 'https://support.createchstudio.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: shortlink
    name: Createch Short Link
    description: 'Save your time, save your link.'
    url: 'https://atcrea.tech'
    method: GET
    expectStatus: 404

  - id: share-drive
    name: Createch Share Drive
    description: 'Ultra fast!'
    url: 'https://drive.createchstudio.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: memos
    name: Createch Memos
    description: 'Your memos, your memories.'
    url: 'https://memos.createchstudio.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: bio-creator
    name: Createch Bio Creator
    description: 'Create your bio in a few seconds.'
    url: 'https://onelink.createchstudio.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blc
    name: Bilibili Live Chat
    description: 'Chat with your friends on Bilibili Live'
    url: 'https://blc.createchstudio.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
